[theme]
primaryColor = "#E5007D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F6FA"
textColor = "#0B3D63"
font = "sans serif"
dataframeHeaderBackgroundColor = "#AFC6E8"
 
[client]
toolbarMode = "minimal"
